let corePrinter = Printer()

/// Registers all built-in functions into the evaluator's core environment.
func registerCoreFunctions(into evaluator: Evaluator) {
    registerArithmeticBasic(into: evaluator)
    registerArithmeticCoercion(into: evaluator)
    registerArithmeticPredicates(into: evaluator)
    registerArithmeticParsing(into: evaluator)
    registerArithmeticPrecision(into: evaluator)
    registerBitwise(into: evaluator)
    registerComparison(into: evaluator)
    registerMacros(into: evaluator)
    registerIO(into: evaluator)
    registerNamespace(into: evaluator)
    registerString(into: evaluator)
    registerPredicates(into: evaluator)
    registerSequenceCore(into: evaluator)
    registerSequenceCollections(into: evaluator)
    registerSequenceVector(into: evaluator)
    registerSequenceArray(into: evaluator)
    registerSequencePredicates(into: evaluator)
    registerHOF(into: evaluator)
    registerMap(into: evaluator)
    registerSet(into: evaluator)
    registerMeta(into: evaluator)
    registerAtom(into: evaluator)
    registerVar(into: evaluator)
    registerWatch(into: evaluator)
    registerConcurrency(into: evaluator)
    registerRef(into: evaluator)
    registerProtocol(into: evaluator)
    registerTransient(into: evaluator)
    registerSort(into: evaluator)
    registerSwiftIONamespace(into: evaluator)
}
